### ISSUE TITLE
Cannot read property prototype of undefined

### ISSUE THREAD

**Issue by SpyceTewan** [TimothyCole/socialblade-js#4]
## Information

**Are you authorized to use the Social Blade API?**
- [ ] Yes

**Node Version:** v8.7.0

**Which new Client method are you using?**
- [x] Auth
- [ ] AuthAsUser

I'm running your example code, and just get this error message.
```javascript
D:\Projects\JavaScript\pewdiepie vs t series\node_modules\request-promise-core\configure\request2.js:34
    var originalInit = options.request.Request.prototype.init;
                                               ^

TypeError: Cannot read property 'prototype' of undefined
    at module.exports (myprojectpath\node_modules\request-promise-core\configure\request2.js:34:48)
    at Object.<anonymous> (myprojectpath\node_modules\request-promise-native\lib\rp.js:15:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (myprojectpath\node_modules\socialblade\lib\client.js:3:17)

```

**Comment by TimothyCole** [comment]
Closed do to unauthorized access to the API
